name: Frontend CI

on:
  push:
    branches: [ master, main, develop, actions ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

  lighthouse:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse
        run: lighthouse http://arquisisproject.me --output=json --output-path=./lighthouse-results.json
